Feature/user menu
Ligerina/TelegramBot pull request #18
Opened 2024-10-20 13:46 UTC by Ligerina

2024-10-28 06:08 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/facade/TelegramBotFacade.java
> +public class TelegramBotFacade extends TelegramLongPollingBot {
а почему фасад? Это ж передняя сторона?  почему не ТелеграмБот как было?

2024-10-31 16:09 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/facade/TelegramBotFacade.java
> +public class TelegramBotFacade extends TelegramLongPollingBot {
Ну по-сути это точка входа запроса в нашего бота. Именно тут сообщение принимается и отправляется назад , поэтому логично, что это передняя сторона 
Телеграм бот можно оставить, но я решил немного разнести - фасад та часть что ближе всего к юзеру, сервис - то что уже ближе к бд, бизнес логике и так далее

2024-11-01 05:52 UTC, rreshrr commented
бро, когда правки??? @Ligerina

2024-11-01 18:39 UTC, rreshrr requested changes
поправить и в продакшен

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/facade/TelegramBotFacade.java
> +        var responseMessage = chatService.handleUserRequest(update);
круто)

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (isUserQuestion(chatId)) {
if (...) {
            return ...
        } 
        else if (...) {
            return ...
        }
        else {
            return ...
        }

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (isUserQuestion(chatId)) {
на подушнить чисто

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (isUserQuestion(chatId)) {
на самом деле хз, в некоторых языках такой код будет оптимизирован процессором на стадии какой-то, ему так расчет делать легче будет, хз как в джаве

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +    public String getStartResponseForUser(String userName) {
опустить под StartCommandReceived)) а то читается не сверху вниз

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        SendMessage message = createMessage(chatId, "Введи свой вопрос");
почему отступил от концепции var?

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (Commands.ALLOWED_COMMAND_AFTER_MODEL_RESPONSE.contains(userText)) {
мб в отдельную статическую функцию класса Commands?

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        return createMessage(chatId, "Пожалуйста, используй одну из преложенных команд ниже");
очепятка

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        var message = new SendMessage();
var message = createMessage(chatId, answer);

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +            ReplyKeyboardRemove keyboardRemove = new ReplyKeyboardRemove();
а че это делает? какая-то клава by default?

2024-11-01 18:39 UTC, rreshrr commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +    private final Map<Long, String> chatState = new HashMap<>();
почему в единственном числе, этожеж коллекция?

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/facade/TelegramBotFacade.java
> +        var responseMessage = chatService.handleUserRequest(update);
Та а че не так то..?

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +    private final Map<Long, String> chatState = new HashMap<>();
Ну у тебя в коллекции хранится стейт чата - чат стейт

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (isUserQuestion(chatId)) {
кажется элсы только сбивают с толку 
Особенно елс ифы

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        SendMessage message = createMessage(chatId, "Введи свой вопрос");
Объебался 
Поправил

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +    public String getStartResponseForUser(String userName) {
Done

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        if (Commands.ALLOWED_COMMAND_AFTER_MODEL_RESPONSE.contains(userText)) {
Мммм 
А го - кажется норм тема 

Добавил

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        return createMessage(chatId, "Пожалуйста, используй одну из преложенных команд ниже");
Done

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +        var message = new SendMessage();
спс - done

2024-11-03 18:04 UTC, Ligerina commented on src/main/java/ru/liger/telegram/bot/service/ChatService.java
> +            ReplyKeyboardRemove keyboardRemove = new ReplyKeyboardRemove();
Класс, который позволяет тебе создать клаву для юзера и эту клаву обогащать как угодно

2024-11-03 19:05 UTC, rreshrr commented
гуд!! в продакшен!!!

2024-11-10 18:47 UTC, merged